name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: dropdown
    id: workflow
    attributes:
      label: Workflow
      description: Which workflow does this apply to?
      options:
        - Apple (Reminders)
        - Microsoft (To Do)
        - Google (Keep)
        - Alfred
        - All workflows
        - Repository / CI
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
      placeholder: A clear description of the feature...
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this is done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
